defaults:
  - train: train
  - model: base
  - optimizer: adam
  - scheduler: base

seed: 42
save_checkpoint: false
criterion:
  _target_: torch.nn.BCEWithLogitsLoss
evaluator:
  _target_: eval.LabelBinEvaluator